### ISSUE TITLE
调用so文件失败

### ISSUE THREAD

**Issue by Surrin1999** [zwxu064/TransInit#1]
我正尝试通过evaluation.sh来测试，在导入bilateralfilter时，通过sys.append(../wrapper/......)改变当前路径来导包时还是显示找不到这个包，然后我就将third_party/rloss/wrapper/bilateralfilter/build/lib.linux-x86_64-3.6下的所有文件拷贝到了DenseCRFLoss的同级目录下，但还是会报这个找不到_bilateralfilter的错误，看您的意思应该是要调用so文件，请问该如何解决呢？
![image](https://user-images.githubusercontent.com/37960540/161304265-0118bd57-058f-472c-abc6-ef08186705f5.png)

![image](https://user-images.githubusercontent.com/37960540/161303755-2df20132-caf9-401a-894b-ab2a2f566c7a.png)

**Comment by zwxu064** [comment]
你好，这个可能是我们使用的平台或者各种依赖包版本不一样导致我仓库里编译后的库没法兼容到你的本地机器。这个模块是rloss仓库的代码，我把它放在了第三方（third_party）。建议你到https://github.com/meng-tang/rloss/tree/master/pytorch看下这个动态库的编译方式，重新在你本地工程编译后使用。

**Comment by zwxu064** [comment]
> 我正尝试通过evaluation.sh来测试，在导入bilateralfilter时，通过sys.append(../wrapper/......)改变当前路径来导包时还是显示找不到这个包，然后我就将third_party/rloss/wrapper/bilateralfilter/build/lib.linux-x86_64-3.6下的所有文件拷贝到了DenseCRFLoss的同级目录下，但还是会报这个找不到_bilateralfilter的错误，看您的意思应该是要调用so文件，请问该如何解决呢？ ![image](https://user-images.githubusercontent.com/37960540/161304265-0118bd57-058f-472c-abc6-ef08186705f5.png)
> 
> ![image](https://user-images.githubusercontent.com/37960540/161303755-2df20132-caf9-401a-894b-ab2a2f566c7a.png)

你好，这个可能是我们使用的平台或者各种依赖包版本不一样导致我仓库里编译后的库没法兼容到你的本地机器。这个模块是rloss仓库的代码，我把它放在了第三方（third_party）。建议你到[https://github.com/meng-tang/rloss/tree/master/pytorch](https://github.com/meng-tang/rloss/tree/master/pytorch)看下这个动态库的编译方式，重新在你本地工程编译后使用。

**Comment by Surrin1999** [comment]
> 

感谢，我重新编译SO文件后已解决
