### ISSUE TITLE
请问valid_area相关的代码可以去掉吗？

### ISSUE THREAD

**Issue by Surrin1999** [zwxu064/TransInit#2]
作者您好，我需要替换您的超像素分割模型为SSN以及我自己的模型在KITTI语义分割数据集上进行语义分割，但是查看您的代码时发现针对loss的计算方面，您比起FCN添加了valid_area相关的代码逻辑，我没懂是啥意思，请问这一部分代码能去掉吗？
![image](https://user-images.githubusercontent.com/37960540/161417668-a0e38c06-939f-4d1d-a058-61d76203d70a.png)

**Comment by Surrin1999** [comment]
我尝试去掉valid_area之后，跑pascal数据集发现loss飙升到了几万，请问您能大概解释一下valid_area的意思吗？为什么会这样呢？

**Comment by Surrin1999** [comment]
好像是为了处理pascal数据集的GT上的白色边缘是吗？是不是GT没有pascal的GT这种白色边缘就不用valid_area相关的代码了呢？

**Comment by zwxu064** [comment]
> 好像是为了处理pascal数据集的GT上的白色边缘是吗？是不是GT没有pascal的GT这种白色边缘就不用valid_area相关的代码了呢？

你好！你的理解是对的。你可以看到TransInit/main.py里valid_area是target为254(随机crop后填充边缘至统一图片大小，这个是我们自己添加的)和255（白色区域为语义分割GT中由于人为标签导致的不确定边缘区域，这个在数据集自身中携带）。如果GT本身有255，但是你在计算语义分割loss时没有将其屏蔽掉，会导致255匹配不到比如21类的标签，loss会很大。如果没有GT本身没有255，valid_area只考虑crop后填充的，就是padding的部分，因为这部分本身不属于分割的一部分。
