### ISSUE TITLE
能否提供所有预训练的权重？

### ISSUE THREAD

**Issue by Surrin1999** [zwxu064/TransInit#3]
作者您好，我看到您的train.sh中，在训练时针对不用情况需要用到众多预训练权重，请问能否公开这些权重呢？谢谢您

**Comment by zwxu064** [comment]
你好！这些预训练的权值：语义分割和超分辨，是脱离本文独立在[rloss](https://github.com/meng-tang/rloss)工程和[superpixel_fcn](https://github.com/fuy34/superpixel_fcn)中单独获取，两者可以分别为各自任务的sota模型，之后用本文方法finetune。train.sh里语义分割的预训练模型是我之前自己复现的结果，之前的服务器里现在找不到这些模型，但是你可以直接从rloss工程里找到原作者训练模型。我这里提供我finetune后的最终模型和superpixel_fcn模型，参考[这里](https://1drv.ms/u/s!AngC1-tRlyPMgk9MTXx8x-8CVLvK?e=NQZvIC)，你可以从里面单独拿出语义分割的deeplab那个模型。
